# Generated by Django 4.1 on 2022-08-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=10)),
                ("precio_compra", models.CharField(max_length=10)),
                ("precio_venta", models.CharField(max_length=10)),
                ("fecha_compra", models.DateTimeField()),
                ("fecha_registro", models.DateTimeField()),
                ("estado", models.CharField(max_length=1)),
            ],
        ),
    ]
