# Generated by Django 4.1 on 2022-08-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=10)),
                ("horas", models.CharField(max_length=10)),
                ("creditos", models.CharField(max_length=10)),
                ("fecha_registro", models.DateTimeField()),
                ("estado", models.CharField(max_length=1)),
            ],
        ),
    ]
